model: 'Vnet(ELU)+Dice'        # used to save the recoder_log
task: 'MultiOrganSeg'        # this will affect the first level parent directory

data_type: 'Data_0604'

network: 'Vnet_Ori'     # this will affect the dictionary for selecting networks

model_dir: 'model/'
record_dir: 'data/record/'

resume: true
gpus: (3, 2, 1, 0)
num_class: 2            # BinerySegmentation
loss: 'Dice'

elu: True
nll: False

data:
    img_type: 'O'        # 'E': enhance, 'O': original
    label_type: 'FLOW'
    DataTransType: 'JustToTensor'
    Act_type: 'no_ZJP'
    Constractioner: 'RandomPatches_xy'
    patch_size: (112, 112, 160)  # x y z

train:
    optim: 'adam'
    lr: 1e-4
    milestones: (300, 600, 1000)
    gamma: 0.5

    batch_size: 4             # for four cards
    dataset: 'OrganSeg_Train_V0'  # @ dataset_catalog
    num_workers: 4
    epoch: 12000         # 0517

test:
    dataset: 'OrganSeg_Test_V0'
    batch_size: 1

save_ep: 200
eval_ep: 200